spring.mvc.view.prefix=/pages/
spring.mvc.view.suffix=.jsp

# Connection url for the database "netgloo_blog"
spring.datasource.url = jdbc:mysql://localhost:3306/UserDB
spring.datasource.username = javaapp
spring.datasource.password = javaapp123
